remote_theme: jekyll/minima

title: Datasmith
email: victor.reyes@datasmith.ca
description: >
  Python, Machine Learning and Data Science

minima:
  social_links:
    github: haveon
    linkedin: vreyesos
    
plugins:
  - jekyll-feed
  - jekyll-seo-tag
