remote_theme: jekyll/minima

title: Datasmith
email: not-a-real@email.com
description: >-
  Peronal website showing off cool projects and random musings on
  Python, data science and machine learning.
github: haveon
linkedin: vreyesos
